import './globals.scss';
import localFont from 'next/font/local';
import AuthProvider from "@/app/_components/auth-provider";
import Footer from "@/app/_components/footer";
import HeaderDesktop from "@/app/_components/header/desktop";
import HeaderMobile from "@/app/_components/header/mobile";

const poppins = localFont({
  src: [
    {
      path: './Poppins-Bold.ttf',
      weight: '700',
      style: 'normal',
      variable: '--font-poppins',
    },
    {
      path: './Poppins-Regular.ttf',
      weight: '400',
      style: 'italic',
      variable: '--font-poppins',
    },
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className={"page-wrapper"}>
            <HeaderDesktop/>
            <HeaderMobile/>
            <main id={"main-content"}>
                {children}
            </main>
            <Footer/>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
