import './globals.scss';
import localFont from 'next/font/local';
import Header from "@/app/_components/header";
import AuthProvider from "@/app/_components/auth-provider";

const poppins = localFont({
  src: [
    {
      path: './Poppins-Bold.ttf',
      weight: '700',
      style: 'normal',
      variable: '--font-poppins',
    },
    {
      path: './Poppins-Regular.ttf',
      weight: '400',
      style: 'italic',
      variable: '--font-poppins',
    },
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header/>
          <main>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
